workflows:
  ios-capacitor:
    name: iOS Capacitor – Build & Sign (Automatic Signing)
    max_build_duration: 120
    instance_type: mac_mini_m1

    environment:
      xcode: latest
      node: 18
      vars:
        BUNDLE_ID: it.gestionescadenze.app
        XCODE_PROJECT: App.xcodeproj
        XCODE_SCHEME: App

    scripts:
      - name: Install Node dependencies
        script: |
          npm ci

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios

      - name: Build signed archive (AUTOMATIC SIGNING)
        script: |
          cd ios/App
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/App.xcarchive \
            archive \
            -allowProvisioningUpdates \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            CODE_SIGN_STYLE=Automatic \
            CODE_SIGN_IDENTITY="Apple Distribution"

      - name: Export IPA
        script: |
          cd ios/App
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist ExportOptions.plist \
            -allowProvisioningUpdates

    artifacts:
      - ios/App/build/ipa/*.ipa
      - ios/App/build/App.xcarchive
