workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    working_directory: frontend
    integrations:
      app_store_connect: Codemagic #this is the appstoreAPI key that you've added under teams >personal account > integrations > developer portal > manage keys
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: it.gestionescadenze.GestioneScadenze
      xcode: latest
      node: 22
      vars:
        XCODE_PROJECT: "frontend/ios/App/App.xcodeproj"
        SCHEME: "App"
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/core @capacitor/cli @capacitor/ios

      - name: Build web app
        script: |
          npm run build

      - name: Setup iOS platform
        script: |

          npx cap add ios
          npx cap sync ios

      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR/ios/App
          agvtool new-version -all 1.0.$(($PROJECT_BUILD_NUMBER))
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --archive-flags="-destination 'generic/platform=iOS'" 

    artifacts:
      - build/ios/xcarchive/*.xcarchive
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration
