workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: Codemagic

    environment:
      xcode: latest
      node: 22
      ios_signing:
        distribution_type: app_store
        bundle_identifier: it.gestionescadenze.app

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios

      - name: Build iOS archive
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            archive \
            CODE_SIGN_STYLE=Automatic

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath ios/App/build/App.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ios-export-options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
