workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: Codemagic

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: it.gestionescadenze.GestioneScadenze
      node: 22.12.0
      xcode: 26.2
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor with iOS
        script: |
          npx cap sync ios

      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files \
            it.gestionescadenze.GestioneScadenze \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --project ios/App/App.xcodeproj \
            --scheme App

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - acaridi57@gmail.com
        notify:
          success: true
          failure: true

      app_store_connect:
        auth: integration
        submit_to_testflight: true
