workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic2
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: it.gestionescadenze.GestioneScadenze
      node: 22.12.0
      xcode: 26.2
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Sync Capacitor with iOS
        script: |
          npx cap sync ios
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App
    artifacts:
      - ios/App/build/ipa/*.ipa
    publishing:
      email:
        recipients:
          - acaridi57@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
