workflows:
  ios-capacitor:
    name: iOS Capacitor – Build & Sign (Automatic Signing)
    max_build_duration: 120
    instance_type: mac_mini_m1
    
    integrations:
      app_store_connect: Codemagic
    
    environment:
      xcode: latest
      node: 22
      ios_signing:
        distribution_type: app_store
        bundle_identifier: it.gestionescadenze.app
      vars: 
        BUNDLE_ID: it.gestionescadenze.app
        XCODE_PROJECT: App.xcodeproj
        XCODE_SCHEME: App
      
    scripts:
      - name: Install Node dependencies
        script: |
          npm install
        
      - name: Build web app
        script: |
          npm run build
            
      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios
            
      - name: Build signed archive (AUTOMATIC SIGNING)
        script: |
          cd ios/App
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/App.xcarchive \
            archive \
            -allowProvisioningUpdates \
            CODE_SIGN_STYLE=Automatic
    
      - name: Export IPA
        script: |
          cd ios/App
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist ../../ios-export-options.plist \
            -allowProvisioningUpdates

    artifacts:
      - ios/App/build/ipa/*.ipa
      - ios/App/build/App.xcarchive
